/*
 * Copyright (c) 2017 Kenton Hamaluik
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
package mammoth.loader;

typedef MammothMeta = {
    /**
     *  The version of Mammoth 3D file this is / was generated by
     */
    var version:String;

    /**
     *  A sanitized version of the source file for this
     */
    @:optional var file:String;

    /**
     *  What version of Blender produced the file
     */
    @:optional var blender:String;
}

typedef MammothFile = {
    /**
     *  Metadata associated with the file / scene
     */
    var meta:MammothMeta;
    
    var cameras:Array<Camera>;
    var lights:Array<Light>;
    var shaders:Array<Shader>;
    var meshes:Array<Mesh>;
    var objects:Array<Object>;
}